name: handy_dandy_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+3

environment:
  sdk: '>=3.0.0-202.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  flutter_svg: ^1.1.0
  # url_launcher: 
  flutter_spinkit:
  package_info_plus: ^4.2.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^10.1.0
  socket_io_client: ^2.0.0-beta.4-nullsafety.0  #2.0.0-beta.4-nullsafety.0    #1.0.2
  uuid: ^3.0.6
  double_back_to_close_app: ^2.1.0
  fluttertoast: ^8.0.9
  android_intent_plus: ^3.1.1
  parse_server_sdk_flutter: ^7.0.1
  connectivity_plus: ^5.0.2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2


flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path: "assets/images/logo_main.png"


# flutter pub get
# flutter pub run flutter_launcher_icons:main

  # flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Regular
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/Vazirmatn-Medium.ttf

    - family: Light
      fonts:
        - asset: assets/fonts/Vazirmatn-Light.ttf

    - family: Bold
      fonts:
        - asset: assets/fonts/Vazirmatn-Bold.ttf
    
    - family: Black
      fonts:
        - asset: assets/fonts/Vazirmatn-Black.ttf
